### ISSUE TITLE
ColmapSlam

### ISSUE THREAD

**Issue by awarebayes** [tforgaard/zuricityslam#1]
Hello, thank you for your awesome work! I am really interested in finding out what ColmapSlam in readme is.

**Comment by tforgaard** [comment]
Thank you! I can send you an email with the contact information of the makers of COLMAPSLAM.

**Comment by awarebayes** [comment]
That would be awesome, my email is awarebayes@gmail.com

**Comment by awarebayes** [comment]
H-hi :)

**Comment by tforgaard** [comment]
Hi again!

I sent you an email a week ago, maybe check your spam folder
